//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EISEntities2 : DbContext
    {
        public EISEntities2()
            : base("name=EISEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aspect> Aspect { get; set; }
        public virtual DbSet<Criteria> Criteria { get; set; }
        public virtual DbSet<DescriptionOfJudgeAspects> DescriptionOfJudgeAspects { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<ProModule> ProModule { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<StatusStudent> StatusStudent { get; set; }
        public virtual DbSet<StatusTeacher> StatusTeacher { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentResult> StudentResult { get; set; }
        public virtual DbSet<SubCriteria> SubCriteria { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemUser> SystemUser { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<TypeAspect> TypeAspect { get; set; }
        public virtual DbSet<Vedomosti> Vedomosti { get; set; }
    }
}
