//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentResult
    {
        public int IdStudentResult { get; set; }
        public int IdStudent { get; set; }
        public int IdAspect { get; set; }
        public string NumberOfPointsForAspects { get; set; }
    
        public virtual Aspect Aspect { get; set; }
        public virtual Student Student { get; set; }
    }
}
